Repository djodjo89/cacompilepas, pull requests merged in 2019-12, with the labels that each got.

#22 CCP-19 feat/back(database): make database 1.0 with testing data
  back/db/database_init.sql
  back/db/database_v1.sql
  back/db/messages.sql
Labels: enhancement

#23 CCP-25: feat/front(logo): first version of logo
  docs/icons/logo.svg
  docs/icons/logos.svg
  docs/icons/new-logo.png
  front/src/App.css
  front/src/App.js
  front/src/Nav.js
  front/src/logo.png
  front/src/logos-2-usable.svg
  front/src/new-logo.png
  front/src/new-logo.svg
Labels: enhancement

#26 Ccp 24
  front/logo.png
  front/src/App.css
  front/src/Nav.js
  front/src/Svg.tsx
Labels: enhancement

#28 CCP-33 docs/docs(pages): new personal space moqup design
  docs/moqups/mon espace.PNG
Labels: documentation

#29 CCP-11 feature/Front(HomePage): new HomePage for a newLife
  front/src/Home.css
  front/src/Home.js
  front/src/Svg.tsx
Labels: enhancement

#33 CCP-21 feat/api(lobby): fix some bugs with data persistance and synta…
  back/App/Controller/AbstractController.php
  back/App/Controller/DefaultController.php
  back/App/Module/ConnectionModule/Controller/ConnectionController.php
  back/App/Module/ConnectionModule/Model/ConnectionModel.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/LobbyModule.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  db/scripts/init.sql
  front/src/API/Request.tsx
  front/src/Home.js
  front/src/View/App.tsx
  front/src/View/Home.tsx
  front/src/css/Home.css
  front/yarn-error.log
  front/yarn.lock
Labels: bug

#31 CCP-37 docs/front(register): make register page moqup
  docs/moqups/inscription.png
Labels: documentation

#37 CCP-40 docs/front(lobby): add lobby modification pages and update lob…
  docs/moqups/lobby creation.png
  docs/moqups/lobby description course sheets.png
  docs/moqups/lobby description modification.png
  docs/moqups/lobby description rights.png
Labels: documentation

#35 CCP-41 docs/front(lobby): update lobby page based on feedback and add…
  docs/moqups/lobby.png
Labels: documentation

#36 CCP-38 docs/front(lobby): add 'new lobby' button in profile page
  docs/moqups/mon espace.PNG
Labels: documentation

#41 CCP-43 feat/back(rights): add lobby rights management
  .gitignore
  back/App/Connection/Connection.php
  back/App/Http/Request.php
  back/App/Model/AbstractModel.php
  back/App/Module/ConnectionModule/Controller/ConnectionController.php
  back/App/Module/ConnectionModule/Model/ConnectionModel.php
  back/App/Module/CourseSheetModule/Model/CourseSheetModel.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Controller/localfile.pdf
  back/App/Module/LobbyModule/Model/LobbyModel.php
  back/composer.json
  back/site-2.conf
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  db/Dockerfile
  db/conf/custom_my.cnf
  db/scripts/init.sql
  docker-compose.yml
  front/cypress/integration/examples/network_requests.spec.js
  front/package-lock.json
  front/package.json
  front/src/API/Request.tsx
  front/src/Security/PrivateRoute.tsx
  front/src/View/App/App.tsx
  front/src/View/App/Upload.tsx
  front/src/View/Connection/Connection.tsx
  front/src/View/Lobby/Lobby.tsx
  ftp/coursesheets/Archi_Little_Boat.pdf
  ftp/img/Colors-Gucci-Logo_1.jpg
  ftp/img/Roi_Arthur_livre_3.jpg
  ftp/img/pink_pencil_case_2.jpg
Labels: enhancement

#44 CCP-50 feat/front(right): add rights page
  back/App/Module/CourseSheetModule/Model/CourseSheetModel.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  db/scripts/init.sql
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/View/Admin/Admin.tsx
  front/src/View/Admin/User.tsx
  front/src/View/Admin/Users.tsx
  front/src/View/App/App.tsx
  front/src/View/App/Upload.tsx
  front/src/View/Connection/Connection.tsx
  front/src/View/General/DropBox.tsx
  front/src/View/General/Input.tsx
  front/src/View/General/InputArea.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/CourseSheets.tsx
  front/src/View/Lobby/Lobby.tsx
  front/src/View/Lobby/Messages.tsx
  front/src/css/Admin.css
  front/src/css/App.css
  front/src/css/CourseSheet.css
  front/src/css/User.css
  front/src/css/index.css
  front/src/img/image-icon.svg
  front/src/img/minus-icon-2.png
  front/src/img/minus-icon-red-t.png
  front/src/img/minus-icon.png
  front/src/img/plus-icon.png
  front/src/img/usable-image-icon.svg
  ftp/coursesheets/Archi_Little_Boat_2.pdf
Labels: enhancement

#42 CCP-50 feat/front(admin): make presentation modification tab
  back/App/Module/LobbyModule/Controller/LobbyController.php
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/View/Admin/Admin.tsx
  front/src/View/App/App.tsx
  front/src/View/App/Upload.tsx
  front/src/View/Connection/Connection.tsx
  front/src/View/General/DropBox.tsx
  front/src/View/General/Input.tsx
  front/src/View/General/InputArea.tsx
  front/src/View/Lobby/Lobby.tsx
  front/src/css/Admin.css
  front/src/img/image-icon.svg
  front/src/img/usable-image-icon.svg
  ftp/coursesheets/Archi_Little_Boat.pdf
Labels: enhancement

#46 CCP-72 feat/api(coursesheet): allow user to consult a coursesheet in a new page
  back/App/Controller/AbstractController.php
  back/App/Http/Request.php
  back/App/Model/AbstractModel.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  back/site-2.conf
  docker-compose.yml
  front/src/API/Request.tsx
  front/src/Security/PrivateRoute.tsx
  front/src/View/Admin/Admin.tsx
  front/src/View/Connection/Connection.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/CourseSheets.tsx
  front/src/View/Lobby/Lobby.tsx
  front/src/View/Lobby/Messages.tsx
Labels: enhancement

#48 CCP-55 feat/front(hashtags): add hashtags to front
  back/App/Controller/AbstractController.php
  back/App/Http/Request.php
  back/App/Http/Router.php
  back/App/Model/AbstractModel.php
  back/App/Module/CourseSheetModule/Controller/CourseSheetController.php
  back/App/Module/CourseSheetModule/CourseSheetModule.php
  back/App/Module/CourseSheetModule/Model/CourseSheetModel.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Controller/localfile.pdf
  back/App/Module/LobbyModule/Model/LobbyModel.php
  back/App/Test/ConnectionModuleTest.php
  db/scripts/init.sql
  front/src/View/Admin/Admin.tsx
  front/src/View/General/Hashtag.tsx
  front/src/View/General/HashtagInput.tsx
  front/src/View/General/Nav.tsx
  front/src/View/General/SearchBar.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/CourseSheets.tsx
  front/src/css/Admin.css
  front/src/css/Hashtag.css
  front/src/css/Nav.css
  front/src/img/cross.svg
Labels: enhancement

#49 Ccp 55 2
  back/App/Controller/AbstractController.php
  back/App/Model/AbstractModel.php
  back/App/Module/CourseSheetModule/Controller/CourseSheetController.php
  back/App/Module/CourseSheetModule/CourseSheetModule.php
  back/App/Module/CourseSheetModule/Model/CourseSheetModel.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  db/scripts/init.sql
  front/src/View/Admin/Admin.tsx
  front/src/View/General/Hashtag.tsx
  front/src/View/General/HashtagInput.tsx
  front/src/View/General/SearchBar.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/CourseSheets.tsx
  front/src/View/Lobby/Lobby.tsx
Labels: enhancement

#51 CCP-71 fix/back(rights): hotfix
  back/App/Module/LobbyModule/Controller/LobbyController.php
  front/src/View/Admin/Admin.tsx
  front/src/View/General/DropBox.tsx
Labels: fix

#50 CCP-70 feat/front(lobby): remake lobby based on external reviews
  front/src/View/General/Divider.tsx
  front/src/View/General/Nav.tsx
  front/src/View/General/SearchBar.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/Lobby.tsx
  front/src/View/Lobby/Message.tsx
  front/src/View/Lobby/Messages.tsx
  front/src/View/Lobby/WriteMessageZone.tsx
  front/src/css/CourseSheet.css
  front/src/css/Lobby.css
  front/src/css/Message.css
  front/src/css/index.css
Labels: enhancement

#52 CCP-71 feat/front(dropbox): make upload cool ;)
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  front/package-lock.json
  front/package.json
  front/src/Security/PrivateRoute.tsx
  front/src/View/Admin/Admin.tsx
  front/src/View/General/DropBox.tsx
  front/src/css/DropBox.css
Labels: enhancement

#53 CCP-51 docs/front(lobby): popular lobbies moqup
  docs/moqups/navbar.png
  docs/moqups/popular-lobbies.png
  docs/moqups/popular-lobbies.png.xd
Labels: enhancement

#54 CCP-54 feat/back(lobby): popular lobbies
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
Labels: enhancement
