Repository djodjo89/cacompilepas, pull requests merged in 2019-11, with the labels that each got.

#1 CCP-2 test(base): test
  README.md
Labels: good first issue

#2 CCP-1 docs(base): add base docs to the project
  docs/Idees projet web.pdf
  docs/Projet php caCompilePas.mcd
  docs/moqups/Capture d’écran 2019-11-09 à 20.31.16.png
  docs/moqups/Capture d’écran 2019-11-09 à 20.31.30.png
Labels: documentation

#3 CCP-4(documentation): MCD v1.0 but could not add anymore relation
  docs/Projet php caCompilePas.mcd
Labels: documentation, invalid

#4 CCP-4 docs(mcd): mcd v1.0 but could not add anymore relation
  docs/Projet php caCompilePas.mcd
Labels: documentation, duplicate

#5 CCP-5 docs/docs(golven): add golven
  README.md
Labels: documentation, good first issue

#6 CCP-4 docs/docs(mcd): restore good mcd version
  docs/Projet php caCompilePas.mcd
Labels: documentation

#7 CCP-4 docs/docs(mcd): split mcd into two parts because of jmerise lim…
  docs/Projet php caCompilePas messages.mcd
  docs/Projet php caCompilePas.mcd
Labels: documentation

#8 CCP-9 feat/model(db): create database and connection class
  back/.project
  back/connection/Connection.php
  back/db/database_init.sql
  back/index.php
  back/model/Model.php
  docs/Projet php caCompilePas.mcd
  front/front/.gitignore
  front/front/README.md
  front/front/package.json
  front/front/public/favicon.ico
  front/front/public/index.html
  front/front/public/logo192.png
  front/front/public/logo512.png
  front/front/public/manifest.json
  front/front/public/robots.txt
  front/front/src/App.css
  front/front/src/App.js
  front/front/src/App.test.js
  front/front/src/index.css
  front/front/src/index.js
  front/front/src/logo.svg
  front/front/src/serviceWorker.js
  front/front/yarn.lock
Labels: enhancement

#9 CCP-4 docs/docs(mcd): Change some manyToMany to manyToOne relations a…
  back/db/base.sql
  back/db/messages.sql
  docs/Projet php caCompilePas messages.mcd
  docs/Projet php caCompilePas.mcd
Labels: documentation, enhancement

#10 CCP-8 docs/api(base): class diagram and api logic schemas
  back/Class Diagram.ucls
  docs/schemas/back/Back API logic.png
  docs/schemas/back/Class Diagram.PNG
Labels: documentation

#12 CCP-17-feat/back(index.php):create index.php class and fix syntaxError
  back/index.php
Labels: enhancement

#11 CCP-19 feat/back(controller): make default controller
  back/App/Connection/Connection.php
  back/App/Controller/DefaultController.php
  back/model/Model.php
Labels: enhancement

#16 Ccp 12
  front/front/public/index.html
  front/front/src/App.js
  front/front/src/Divider.js
  front/front/src/Footer.js
  front/front/src/LargeDivider.js
  front/front/src/Lobby.js
  front/front/src/Nav.js
  front/front/src/example.png
  front/front/src/icon-female-user.svg
  front/front/src/index.css
  front/front/yarn.lock
Labels: enhancement

#14 CCP-14
  back/App/Connection/Connection.php
  back/App/index.php
  docs/moqups/lobby.png
  docs/moqups/page d'accueil.png
Labels: documentation

#17 CCP-13 feat/api(connection): make connection api route in front and back
  back/App/Controller/DefaultController.php
  front/front/public/index.html
  front/front/src/Api.js
  front/front/src/App.js
  front/front/src/cs-icon.png
Labels: enhancement

#19 CCP-22 feat/api(connection): make connection module and dockerize
  .env
  back/App/Connection/Connection.php
  back/App/ConnectionModule/ConnectionModule.php
  back/App/ConnectionModule/Controller/ConnectionController.php
  back/App/ConnectionModule/Model/ConnectionModel.php
  back/App/Controller/AbstractController.php
  back/App/Controller/DefaultController.php
  back/App/Model/AbstractModel.php
  back/App/Module/AbstractModule.php
  back/Dockerfile
  back/index.html
  back/index.php
  back/site-2.conf
  docker-compose.yml
  front/.dockerignore
  front/.gitignore
  front/Dockerfile
  front/README.md
  front/front/src/Api.js
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.js
  front/src/App.test.js
  front/src/Divider.js
  front/src/Footer.js
  front/src/LargeDivider.js
  front/src/Lobby.js
  front/src/Nav.js
  front/src/Request.js
  front/src/cacompilepas.code-workspace
  front/src/cs-icon.png
  front/src/example.png
  front/src/icon-female-user.svg
  front/src/index.css
  front/src/index.js
  front/src/logo.svg
  front/src/serviceWorker.js
  front/yarn.lock
  public/index.html
Labels: enhancement

#18 Ccp 23
  back/App/Connection/Connection.php
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/Divider.js
  front/src/Footer.js
  front/src/LargeDivider.js
  front/src/Lobby.js
  front/src/Nav.js
  front/src/NotFound.js
  front/src/index.css
Labels: enhancement

#13 CCP-18(back) : Create CourseSheetModule
  back/CourseSheetModule/CourseSheetController.php
  back/CourseSheetModule/CourseSheetMod.php
  back/CourseSheetModule/CourseSheetModel.php
  back/CourseSheetModule/CourseSheetView.php
Labels: enhancement
