Repository djodjo89/cacompilepas, pull requests merged in 2020-01, with the labels that each got.

#59 CCP-61 feat/back(search): final search implementation
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  front/src/View/General/Nav.tsx
  front/src/View/Public/PublicLobbies.tsx
Labels: enhancement

#62 CCP-73 feat/back(personal): personal information and owned lobbies
  back/App/Model/AbstractModel.php
  back/App/Module/ConnectionModule/Controller/ConnectionController.php
  back/App/Module/ConnectionModule/Model/ConnectionModel.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  db/scripts/init.sql
Labels: enhancement

#65 CCP-58 feat/back(message): add message
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
Labels: enhancement

#68 CCP-74 feat/front(lobby): add course sheets pdf preview
  back/App/Module/LobbyModule/Controller/LobbyController.php
  front/src/View/Lobby/CourseSheet.tsx
  front/src/css/CourseSheet.css
Labels: enhancement

#69 CCP-75 feat/front(lobby): display logo
  back/App/Module/LobbyModule/Model/LobbyModel.php
  front/src/View/Lobby/Lobby.tsx
  front/src/css/Lobby.css
Labels: enhancement

#70 CCP-76 feat/front(admin): display lobby logo
  back/App/Module/LobbyModule/Controller/LobbyController.php
  front/src/View/Admin/Admin.tsx
  front/src/View/General/DropBox.tsx
Labels: enhancement

#71 CCP-77 feat/front(coursesheet): open coursesheet pdf in a new page wih react-pdf
  front/src/View/App/App.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/Lobby.tsx
  front/src/View/Pages/CourseSheetPage.tsx
  front/src/css/PublicLobbies.css
Labels: enhancement

#72 CCP-78 fix/back(coursesheet): ftp course sheet delete
  back/App/Module/CourseSheetModule/Model/CourseSheetModel.php
Labels: enhancement

#74 CCP-67 fix/api(lobby): some hotfixes on api calls
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  front/src/View/Admin/Admin.tsx
  front/src/View/Lobby/Lobby.tsx
  front/src/View/Lobby/Messages.tsx
Labels: enhancement

#73 CCP-64 feat/front(Connection)- We can see if we are connected or not
  front/src/View/General/Nav.tsx
Labels: enhancement

#77 Revert "CCP-64 feat/front(Connection)- We can see if we are connected or not"
  front/src/View/General/Nav.tsx
Labels: bug

#79 CCP-66 feat/api(connection): disconnect button
  back/App/Module/ConnectionModule/Controller/ConnectionController.php
  back/App/Module/ConnectionModule/Model/ConnectionModel.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  front/src/View/Admin/Admin.tsx
  front/src/View/General/Nav.tsx
  front/src/View/General/SearchBar.tsx
  front/src/View/General/SubmitButton.tsx
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobby.tsx
  front/src/css/Nav.css
  front/src/css/index.css
Labels: enhancement

#76 CCP-67 feat/back(connection): disconnect action
  back/App/Module/ConnectionModule/Controller/ConnectionController.php
  back/App/Module/ConnectionModule/Model/ConnectionModel.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobby.tsx
Labels: enhancement

#80 CCP-66 fix/front(connection): logout icon
  front/src/img/logout-icon.png
  ftp/coursesheets/les-lambdas_1.pdf
Labels: fix

#82 CCP-66-2 fix/back(lobby): hotfix find user inexistant
  api/Cacompilepas.postman_collection.json
  back/App/Module/LobbyModule/Model/LobbyModel.php
Labels: fix

#81 CCP-81(docs) : links of the google docs sprint retrospective and the …
  docs/caCompilePas - Historique Rétro + Conventions.pdf
Labels: documentation

#83 CCP-64 feat/front(connection): display when connected
  front/src/View/General/Nav.tsx
Labels: enhancement

#84 CCP-44 feat/back(lobby): delete lobby
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  db/scripts/init.sql
Labels: enhancement

#86 CCP-48 feat/front(lobby): delete lobby button and confirm
  front/package-lock.json
  front/package.json
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobbies.tsx
  front/src/View/Public/PublicLobby.tsx
  front/src/css/Personal.css
Labels: enhancement

#88 CCP-45 feat/api(lobby): creation lobby
  back/App/Model/AbstractModel.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  back/uploads.ini
  docker-compose.yml
  front/src/View/Admin/Admin.tsx
  front/src/View/App/App.tsx
  front/src/View/Pages/LobbyCreation.tsx
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobbies.tsx
  front/src/View/Public/PublicLobby.tsx
Labels: enhancement

#92 CCP-92 fix/front(general): fix some graphic bugs and ui problems
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  front/src/Security/PrivateRoute.tsx
  front/src/View/Admin/Admin.tsx
  front/src/View/App/App.tsx
  front/src/View/Connection/Connection.tsx
  front/src/View/General/HashtagInput.tsx
  front/src/View/General/SearchBar.tsx
  front/src/View/Lobby/Lobby.tsx
  front/src/View/Lobby/Message.tsx
  front/src/View/Pages/LobbyCreation.tsx
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobby.tsx
  front/src/css/Hashtag.css
  front/src/css/Nav.css
  front/src/css/SearchBar.css
Labels: enhancement

#91 CCP-91 feat/front(lobby): add links in interface
  front/src/View/Lobby/Lobby.tsx
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobby.tsx
Labels: enhancement

#93 CCP-27 feat/back(register): add user register
  back/App/Http/Request.php
  back/App/Module/ConnectionModule/Controller/ConnectionController.php
  back/App/Module/ConnectionModule/Model/ConnectionModel.php
  back/App/Module/CourseSheetModule/Model/CourseSheetModel.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  ftp/logo/logo_1.png
Labels: enhancement

#100 CCP-86 test/front(admin): test admin rights
  back/App/Module/CourseSheetModule/Model/CourseSheetModel.php
  front/cypress/fixtures/TP13AbrSortedSet.pdf
  front/cypress/fixtures/UndoCinema.pdf
  front/cypress/fixtures/logo.png
  front/cypress/fixtures/new-logo.png
  front/cypress/integration/ccp/admin.course.sheets.spec.js
  front/cypress/integration/ccp/admin.description.spec.js
  front/cypress/integration/ccp/admin.rights.spec.js
  front/cypress/integration/ccp/bundle.js
  front/cypress/integration/ccp/connection.spec.js
  front/cypress/integration/ccp/lobby.spec.js
  front/cypress/support/commands.js
  front/package-lock.json
  front/package.json
  front/src/View/Admin/Admin.tsx
  front/src/View/Admin/User.tsx
  front/src/View/General/DropBox.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Pages/LobbyCreation.tsx
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobby.tsx
  front/src/css/Admin.css
  front/src/css/index.css
Labels: enhancement

#96 CCP-85 test/front(admin): test admin description update
  front/cypress/integration/ccp/admin.spec.js
  front/cypress/integration/ccp/bundle.js
  front/cypress/integration/ccp/connection.spec.js
  front/cypress/integration/ccp/lobby.spec.js
  front/cypress/support/commands.js
  front/package-lock.json
  front/package.json
  front/src/View/Admin/Admin.tsx
  front/src/View/General/DropBox.tsx
  front/src/View/Pages/LobbyCreation.tsx
Labels: enhancement

#105 CCP-108 feat/front(coursesheet): add dynamic course sheet author name
  back/App/Module/LobbyModule/Model/LobbyModel.php
  db/scripts/init.sql
  front/src/Model/Month.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/CourseSheets.tsx
  front/src/View/Lobby/Message.tsx
  front/src/css/CourseSheet.css
Labels: enhancement

#107 CCP-105 feat/front(messages): delete messages
  back/App/Http/Router.php
  back/App/Module/ConnectionModule/ConnectionModule.php
  back/App/Module/CourseSheetModule/Controller/CourseSheetController.php
  back/App/Module/CourseSheetModule/CourseSheetModule.php
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/LobbyModule.php
  back/App/Module/MessageModule/Controller/MessageController.php
  back/App/Module/MessageModule/MessageModule.php
  front/src/View/Pages/Home.tsx
Labels: enhancement

#108 CCP-29 feat/front(register): make register page
  back/App/Module/ConnectionModule/Model/ConnectionModel.php
  front/cypress/fixtures/icon-female-user.png
  front/cypress/integration/ccp/admin.course.sheets.spec.js
  front/cypress/integration/ccp/admin.description.spec.js
  front/cypress/integration/ccp/admin.rights.spec.js
  front/cypress/integration/ccp/connection.spec.js
  front/cypress/integration/ccp/lobby.spec.js
  front/cypress/integration/examples/actions.spec.js
  front/cypress/integration/examples/aliasing.spec.js
  front/cypress/integration/examples/assertions.spec.js
  front/cypress/integration/examples/connectors.spec.js
  front/cypress/integration/examples/cookies.spec.js
  front/cypress/integration/examples/cypress_api.spec.js
  front/cypress/integration/examples/files.spec.js
  front/cypress/integration/examples/local_storage.spec.js
  front/cypress/integration/examples/location.spec.js
  front/cypress/integration/examples/misc.spec.js
  front/cypress/integration/examples/navigation.spec.js
  front/cypress/integration/examples/network_requests.spec.js
  front/cypress/integration/examples/querying.spec.js
  front/cypress/integration/examples/spies_stubs_clocks.spec.js
  front/cypress/integration/examples/traversal.spec.js
  front/cypress/integration/examples/utilities.spec.js
  front/cypress/integration/examples/viewport.spec.js
  front/cypress/integration/examples/waiting.spec.js
  front/cypress/integration/examples/window.spec.js
  front/cypress/plugins/bundle.js
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/src/API/Request.tsx
  front/src/View/Admin/Admin.tsx
  front/src/View/App/App.tsx
  front/src/View/Connection/ConnectedStatus.tsx
  front/src/View/Connection/Connection.tsx
  front/src/View/Connection/Inscription.tsx
  front/src/View/General/Input.tsx
  front/src/View/Lobby/LobbyCreation.tsx
  front/src/css/Connection.css
  front/src/css/index.css
  front/src/img/new-logo-2.ico
  ftp/icon/Colors-Gucci-Logo_1.jpg
  ftp/icon/Colors-Gucci-Logo_7.jpg
  ftp/icon/Roi_Arthur_livre1_3.jpg
  ftp/icon/Roi_Arthur_livre_3.jpg
  ftp/icon/alarm_5.png
  ftp/icon/icon-female-user_10.png
  ftp/icon/pink_pencil_case_2.jpg
  ftp/icon/pink_pencil_case_23.jpg
Labels: enhancement

#115 CCP-98 docs/back(model): update mcd
  back/App/Module/LobbyModule/Controller/LobbyController.php
  back/App/Module/LobbyModule/Model/LobbyModel.php
  docs/Projet php caCompilePas messages.mcd
  docs/Projet php caCompilePas.mcd
  docs/conventions/Conventions et charte graphique.pdf
  docs/conventions/caCompilePas - Historique Rétro + Conventions.pdf
  docs/produit/Idees projet web.pdf
  docs/remarques mr bossard.txt
  docs/schemas/back/MCD_cacompilepas_final.png
  front/src/API/Request.tsx
  front/src/View/Admin/Admin.tsx
  front/src/View/Admin/User.tsx
  front/src/View/Admin/Users.tsx
  front/src/View/Connection/ConnectedStatus.tsx
  front/src/View/Connection/Connection.tsx
  front/src/View/Connection/Inscription.tsx
  front/src/View/General/Inputs/DropBox.tsx
  front/src/View/General/Inputs/Input.tsx
  front/src/View/General/Inputs/InputArea.tsx
  front/src/View/General/Inputs/RemoveButton.tsx
  front/src/View/General/Inputs/SubmitButton.tsx
  front/src/View/General/Nav.tsx
  front/src/View/General/ProposalList.tsx
  front/src/View/Hashtags/Hashtag.tsx
  front/src/View/Hashtags/HashtagInput.tsx
  front/src/View/Lobby/CourseSheet.tsx
  front/src/View/Lobby/LobbyCreation.tsx
  front/src/View/Lobby/LobbyDescription.tsx
  front/src/View/Lobby/LobbySummary.tsx
  front/src/View/Lobby/Message.tsx
  front/src/View/Lobby/Messages.tsx
  front/src/View/Lobby/WriteMessageZone.tsx
  front/src/View/Pages/NotFound.tsx
  front/src/View/Pages/Personal.tsx
  front/src/View/Public/PublicLobby.tsx
  front/src/View/Search/LobbyProposal.tsx
  front/src/View/Search/Proposal.tsx
  front/src/View/Search/ProposalList.tsx
  front/src/View/Search/SearchBar.tsx
  front/src/View/Search/UserProposal.tsx
  front/src/css/SearchBar.css
  ftp/icon/pink_pencil_case_1.jpg
  ftp/logo/Roi_Arthur_livre1_5.jpg
Labels: enhancement

#111 CCP-94 feat/back(Database) - Delete privileges
  db/scripts/init.sql
Labels: enhancement

#117 CCP-120 feat/front (swal) - Fix swal timer
  front/src/View/Admin/Admin.tsx
  front/src/View/Connection/Inscription.tsx
  front/src/View/Lobby/LobbyCreation.tsx
Labels: fix

#122 CCP-93 feat/front(coursesheet): make coursesheet preview clickable
  cacompilepas/front/src/View/CourseSheet/CourseSheet.tsx
Labels: enhancement

#123 CCP-115 chore/front(lobby): add link to admin in lobby
  cacompilepas/back/App/Module/UserModule/Model/UserModel.php
  cacompilepas/front/node_modules/.cache/babel-loader/1836eb787a6094d04788e19fc672ddc0.json
  cacompilepas/front/node_modules/.cache/babel-loader/1dc3bd9011d15c48c29344f8aa865ad6.json
  cacompilepas/front/node_modules/.cache/babel-loader/29d1aa36e41a1123b434c75030f8b363.json
  cacompilepas/front/node_modules/.cache/babel-loader/77a684c012a7e125ff65d657c002cceb.json
  cacompilepas/front/node_modules/.cache/babel-loader/ba1effd1ca77e9e6bbab7af0de630d84.json
  cacompilepas/front/node_modules/.cache/eslint-loader/21c99a3b31e4005003518cc9c008801680715397.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/5ab62512fbfd13a06df5ef785caf07b3bd25de92.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/88dce3e644fe02e8cc88caffc139442bc7228807.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/8d2cf7ec80e19a67073067fbc1f9de32498c0d7c.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/ecebe72572dfe1832a4e7d01f29275389fecf9eb.json.gz
  cacompilepas/front/src/View/Admin/Admin.tsx
  cacompilepas/front/src/View/Lobby/LobbyDescription.tsx
  cacompilepas/front/src/View/Lobby/LobbyPage.tsx
  cacompilepas/front/src/View/Lobby/LobbyTop.tsx
  cacompilepas/front/src/View/Message/Message.tsx
  cacompilepas/front/src/View/Search/ProposalList.tsx
  cacompilepas/front/src/css/Lobby.css
  cacompilepas/ftp/course_sheets/UndoCinema_4.pdf
  cacompilepas/ftp/icon/icon-female-user_3.png
Labels: enhancement

#124 CCP-125 fix/front(admin): fix swal message when creating bad course s…
  cacompilepas/front/src/View/Admin/Admin.tsx
  cacompilepas/front/src/css/DropBox.css
Labels: enhancement

#125 CCP-112 chore/front(all): refresh data automatically when necessary
  cacompilepas/front/cypress/integration/ccp/admin.description.spec.js
  cacompilepas/front/cypress/integration/ccp/admin.rights.spec.js
  cacompilepas/front/src/View/Admin/Admin.tsx
  cacompilepas/front/src/View/Lobby/LobbyPage.tsx
  cacompilepas/front/src/View/Public/PublicLobbies.tsx
  cacompilepas/front/src/cacompilepas.code-workspace
Labels: enhancement

#126 CCP-112 chore/front(lobby): make lobby logo facultative
  cacompilepas/back/App/Exception/IncorrectFileExtension.php
  cacompilepas/back/App/Model/AbstractFileModel.php
  cacompilepas/back/App/Module/ConnectionModule/Controller/ConnectionController.php
  cacompilepas/back/App/Module/ConnectionModule/Model/ConnectionModel.php
  cacompilepas/back/App/Module/LobbyModule/Controller/LobbyController.php
  cacompilepas/back/App/Module/LobbyModule/Model/LobbyModel.php
  cacompilepas/front/src/View/General/Inputs/DropBox.tsx
  cacompilepas/front/src/View/Lobby/LobbyCreation.tsx
  cacompilepas/front/src/css/DropBox.css
Labels: enhancement

#127 CCP-126 chore/front(upload): change coursesheet upload icon
  cacompilepas/front/src/View/Admin/Admin.tsx
  cacompilepas/front/src/View/General/Inputs/DropBox.tsx
  cacompilepas/front/src/css/Admin.css
  cacompilepas/front/src/css/DropBox.css
Labels: enhancement

#128 CCP-131 chore/front(message): improve messages bodies and write zone
  cacompilepas/back/App/Http/Request.php
  cacompilepas/front/src/View/Admin/Admin.tsx
  cacompilepas/front/src/View/General/Inputs/Input.tsx
  cacompilepas/front/src/View/General/Inputs/SubmitButton.tsx
  cacompilepas/front/src/View/Lobby/LobbyBody.tsx
  cacompilepas/front/src/View/Lobby/LobbyPage.tsx
  cacompilepas/front/src/View/Message/Message.tsx
  cacompilepas/front/src/View/Message/WriteMessageZone.tsx
  cacompilepas/front/src/css/Message.css
  cacompilepas/front/src/css/index.css
Labels: enhancement

#131 CCP-124 fix/front(lobby): hotfix lobby creation
  cacompilepas/back/App/Connection/Connection.php
  cacompilepas/back/App/Http/Request.php
  cacompilepas/back/App/Model/AbstractModel.php
  cacompilepas/back/App/Module/LobbyModule/Model/LobbyModel.php
  cacompilepas/front/package-lock.json
  cacompilepas/front/package.json
  cacompilepas/front/src/View/App/App.tsx
  cacompilepas/front/src/View/General/Nav.tsx
  cacompilepas/front/src/View/Lobby/LobbyCreation.tsx
  cacompilepas/front/src/View/Navigation/BreadCrumCollapser.tsx
  cacompilepas/front/src/View/Navigation/Breadcrumb.tsx
  cacompilepas/front/src/View/Navigation/BreadcrumbItem.tsx
  cacompilepas/front/src/View/Navigation/BreadcrumbSeparator.tsx
  cacompilepas/front/src/View/Navigation/Nav.tsx
  cacompilepas/front/src/css/DropBox.css
  cacompilepas/front/src/css/Nav.css
  cacompilepas/front/src/css/index.css
  cacompilepas/front/src/img/admin.png
  cacompilepas/front/src/img/pdf.svg
  cacompilepas/front/src/react-app-env.d.ts
Labels: enhancement

#133 CCP-116 chore/front(lobby): allow to create course sheet in lobby
  cacompilepas/front/src/View/CourseSheet/CourseSheet.tsx
  cacompilepas/front/src/View/General/Inputs/DropBox.tsx
  cacompilepas/front/src/View/Lobby/LobbyBody.tsx
  cacompilepas/front/src/View/Message/WriteMessageZone.tsx
  cacompilepas/front/src/css/DropBox.css
  cacompilepas/front/src/css/Lobby.css
  cacompilepas/ftp/course_sheets/Archi_Little_Boat_4.pdf
  cacompilepas/ftp/course_sheets/Archi_Little_Boat_6.pdf
  cacompilepas/ftp/course_sheets/Avec textes DROIT des TIC Semaine du 4 novembre Les contrats de développement de logiciels_4.pdf
  cacompilepas/ftp/course_sheets/Avec textes DROIT des TIC Semaine du 4 novembre Les contrats de développement de logiciels_5.pdf
  cacompilepas/ftp/course_sheets/Avec textes DROIT des TIC Semaine du 4 novembre Les contrats de développement de logiciels_6.pdf
  cacompilepas/ftp/course_sheets/B-PSU-400_malloc_7.pdf
  cacompilepas/ftp/course_sheets/Controle de système S3_8.pdf
  cacompilepas/ftp/course_sheets/UndoCinema_7.pdf
  cacompilepas/ftp/course_sheets/UndoCinema_8.pdf
  cacompilepas/ftp/course_sheets/UndoCinema_9.pdf
  cacompilepas/ftp/img/Roi_Arthur_livre1_3.jpg
  cacompilepas/ftp/img/Roi_Arthur_livre_3.jpg
  cacompilepas/ftp/img/pink_pencil_case_2.jpg
  cacompilepas/ftp/logo/Colors-Gucci-Logo_1.jpg
  cacompilepas/ftp/logo/admin_21.png
  cacompilepas/ftp/logo/logo_1.png
Labels: enhancement

#140 CCP-69-3 fix/front(all): some other hotfixes
  cacompilepas/front/src/View/Admin/User.tsx
  cacompilepas/front/src/View/App/App.tsx
  cacompilepas/front/src/View/Connection/Register.tsx
  cacompilepas/front/src/View/Hashtag/HashtagInput.tsx
  cacompilepas/front/src/View/Lobby/LobbyBody.tsx
  cacompilepas/front/src/View/Lobby/LobbyPage.tsx
  cacompilepas/front/src/View/Message/Message.tsx
  cacompilepas/front/src/View/Message/Messages.tsx
  cacompilepas/front/src/View/Pages/Personal.tsx
Labels: fix

#142 CCP-121 feat/front (Inscription): add description password
  cacompilepas/front/node_modules/.cache/babel-loader/06baa9998baa54dbeb58b8dde9fee669.json
  cacompilepas/front/node_modules/.cache/babel-loader/24a582e71c229794811c02ec0711a3a1.json
  cacompilepas/front/node_modules/.cache/babel-loader/2512c110486a3d893c93acaef70a04f9.json
  cacompilepas/front/node_modules/.cache/babel-loader/49fdbae6a27cf4e007cae612de40e243.json
  cacompilepas/front/node_modules/.cache/babel-loader/513c0f594e36d11378d0434ac8f68901.json
  cacompilepas/front/node_modules/.cache/babel-loader/57e4ac0374f28ee9c6678e21f50ec1d5.json
  cacompilepas/front/node_modules/.cache/babel-loader/5f7e9c3c5322470b97519ca75114fd02.json
  cacompilepas/front/node_modules/.cache/babel-loader/664013ca2e6476b28af5b673587f1c46.json
  cacompilepas/front/node_modules/.cache/babel-loader/6bdc37e2bfa414dd39690a17595f38d4.json
  cacompilepas/front/node_modules/.cache/babel-loader/7cf456fbe4b12dc782b592561bd97f62.json
  cacompilepas/front/node_modules/.cache/babel-loader/9487fce056cebbab6a5bc13a1b27f0aa.json
  cacompilepas/front/node_modules/.cache/babel-loader/c9b9723117cbb9b4a88633c269d8af03.json
  cacompilepas/front/node_modules/.cache/babel-loader/db5fa5eab635d8188295f93920791401.json
  cacompilepas/front/node_modules/.cache/babel-loader/f957b9dc0fd6282b7d2521b86b884ac6.json
  cacompilepas/front/node_modules/.cache/eslint-loader/26b31fdad61f29cdb6690ae23e0f96d44c7bac64.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/3c1a36dec71fb487f78213d4e9b00cfb691085b9.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/582d68034cece3a9f771db583294404a50fcbf71.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/5880ee093b4b7ff6522cbbe105c1337a9288fe39.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/6b227d6ef123fa3facac6869723f8eae6f5c2997.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/74c8604d3acf5db0831320dce858af6107cdaf49.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/7dd881aae67b0764206efe083d995236483b0db4.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/a3014d6e705fa720d5d94e640f9a579ce7f97b90.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/a8b4bdda264d1fb9755c04070cfef4bf99e6a9f5.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/c1e0b2d322f56ef8af90ac0c29fe00a5561fefa9.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/c491792bf81c5ae98bfcf6b31bea42365807bb2c.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/c9027b9211380d42248002229ec8b3f4098ddf92.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/d3ef67dae3309190846fcf2f4c2ce808b7f55c7c.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/ea2a32d729fd419552d2bd4c5c9df177a82b165a.json.gz
  cacompilepas/front/node_modules/.cache/eslint-loader/eca4d21a7f135fa93949043276325b09f15d0d23.json.gz
  cacompilepas/front/src/View/Connection/Register.tsx
  cacompilepas/front/src/View/Pages/Home.tsx
Labels: enhancement

#139 CCP-81 docs/docs(artefacts) : Added the newest version of the docs
  cacompilepas/docs/conventions/caCompilePas - Conventions Projet.pdf
  cacompilepas/docs/conventions/caCompilePas - Conventions et charte graphique.pdf
  cacompilepas/docs/conventions/caCompilePas - Historique Rétro + Conventions.pdf
  cacompilepas/docs/conventions/caCompilePas - Liens vers les documentations du projet.pdf
  cacompilepas/docs/produit/Idees projet web.pdf
  cacompilepas/docs/produit/caCompilePas - Présentation générale du projet.pdf
  docs/caCompilePas - Conventions Projet.pdf
  docs/caCompilePas - Conventions et charte graphique.pdf
  docs/caCompilePas - Liens vers les documentations du projet .pdf
  docs/caCompilePas - Liens vers les documentations du projet.pdf
  docs/caCompilePas - Présentation générale du projet.pdf
Labels: documentation

#144 CCP-69 fix/front(admin): add write right message hotfix
  cacompilepas/front/src/View/Admin/User.tsx
Labels: fix
